name: UR Monitor

on:
  schedule:
    - cron: "*/10 * * * *"

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          pip install selenium requests

      - env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
